service: http-relay

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-python-requirements
custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ca-central-1

functions:
  relay:
    handler: relay.main
    memorySize: 256
    timeout: 60
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    environment:
      HOST_URL: ${env:HOST_URL}
      USERNAME: ${env:USERNAME}
      PASSWORD: ${env:PASSWORD}
    events:
      - http:
          path: /{any+}
          method: any
