service: http-relay

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-python-requirements

custom:
  stage: ${opt:stage, self:provider.stage}
  pythonRequirements:
    layer:
      name: ${self:service}

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ca-central-1

functions:
  relay:
    handler: relay.main
    memorySize: 256
    timeout: 60
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    environment:
      HOST_URL: ${env:HOST_URL}
      USERNAME: ${env:USERNAME}
      PASSWORD: ${env:PASSWORD}
    events:
      - http:
          path: /{any+}
          method: any
